### PR TITLE
Refactor DBIC into a better place and streamline usage

### PR DESCRIPTION
**Pull request by nerdstrike**
Refactor DBIC test harness into a more modular location, and remove lazy load behaviour so that its configuration can be pillaged for creating DBConnections. Remove any references to DBIC Schema loader, we will use the DBIC schema to generate the database rather than the other way around.

### CODE REVIEW

**Comment by avullo** [comment]
@markmcdowall the Moose dependency doesn't seem to be an issue, Travis's been happy with the equivalent version included in the test directory.

**Comment by markmcdowall** [comment]
@avullo that's odd as when I tried running the code locally without Moose installed I got the following error:
```
Can't locate Moose.pm in @INC (you may need to install the Moose module)
```
Perhaps Travis includes Moose as part of the base package of perl modules by default

**Comment by nerdstrike** [comment]
Travis has Moose, DBI, and a few other key packages cached by default. You're right, when Prem told me he had added stuff to the cpanfile, I presumed wrongly that Moose was in there along with DBIC. I'll add it.

**Comment by avullo** [comment]
Ah, well spotted :+1:

**Pull request merged**
